[package]
name = "other"
version = "0.1.0"
authors = ["Sebastian RÃ¼th <sebirueth@gmx.de>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
num = "*"
image = "*"
